services:
  - type: web
    name: tracking-student-postgres-api
    env: python
    repo: https://github.com/nickperi/Student-Conduct-Tracker.git
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'gunicorn wsgi:app'
    envVars:
      - fromGroup: tracking-student-postgres-api-settings
      - key: POSTGRES_URL
        fromDatabase:
          name: tracking-student-postgres-api-db
          property: host
      - key: POSTGRES_USER
        fromDatabase:
          name: tracking-student-postgres-api-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: tracking-student-postgres-api-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: tracking-student-postgres-api-db
          property: database

envVarGroups:
  - name: tracking-student-postgres-api-settings
    envVars:
      - key: ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py

databases:
  - name: tracking-student-postgres-api-db
    plan: free
    databaseName: mydb